"""remove idempotency fields

Revision ID: 98797c264df3
Revises: 49dfcf26da5e
Create Date: 2026-08-07 13:18:08.244813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98797c264df3'
down_revision: Union[str, Sequence[str], None] = '49dfcf26da5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_customer_business_identity'), 'customers', type_='unique')
    op.drop_constraint(op.f('uq_customer_idempotency_key'), 'customers', type_='unique')
    op.drop_column('customers', 'request_hash')
    op.drop_column('customers', 'response_cache')
    op.drop_column('customers', 'idempotency_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('idempotency_key', sa.VARCHAR(length=80), nullable=True))
    op.add_column('customers', sa.Column('response_cache', sa.TEXT(), nullable=True))
    op.add_column('customers', sa.Column('request_hash', sa.VARCHAR(length=64), nullable=True))
    op.create_unique_constraint(op.f('uq_customer_idempotency_key'), 'customers', ['idempotency_key'])
    op.create_unique_constraint(op.f('uq_customer_business_identity'), 'customers', ['business_name_normalized', 'business_type_normalized'])
    # ### end Alembic commands ###
